aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  transfer-restart: true
  root: E:\Code\Golang\fresh-shop-group\fresh-shop
  server: /server
  server-api: /api/v1/%s
  server-plug: /plugin/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: fresh-shop/server
captcha:
  key-long: 3
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600
cors:
  mode: strict-whitelist
  whitelist:
    - allow-origin: example1.com
      allow-methods: POST, GET
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
        Content-Type
      allow-credentials: true
    - allow-origin: example2.com
      allow-methods: GET, POST
      allow-headers: content-type
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
        Content-Type
      allow-credentials: true
db-list:
  - disable: false
    type: "mysql"
    alias-name: "freshShopMysql"
    path: "fungs.cn"
    port: "3306"
    config: "charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
    db-name: "fresh-shop"
    username: "fresh-shop"
    password: "eLhGCTg5wWLchb"
    prefix: ""
    singular: false
    engine: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: "Warn"
    log-zap: false
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  signing-key: f6269d62-5947-40fc-9b65-e1ec960542aa
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
local:
  path: uploads/file
  store-path: uploads/file
mssql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
mysql:
  path: qiyundongpin.cn
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  db-name: fresh-shop
  username: fresh-shop
  password: "b14939a081f4bf27"
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: Info
  log-zap: false
oracle:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 48888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  router-prefix: ""
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: fresh-shop/server
timer:
  start: true
  spec: '@daily'
  with_seconds: false
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 168h
zap:
  level: info
  prefix: '[fresh-shop/server]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

wechat:
  appid: 'wxdd9fa969ce0103ce'
  secret: '52e293574b7ae428307965d6f31228fe'
  randomPassword: 'baHVfhZDsQc9yh' # 微信注册的用户初始密码

  #wechatPay:
  #mchId: '1641513718' # 商户号
  #apiV2Key: 'HC7saiqiuqiyundongku13527326320Q'
  #  notifyUrl: 'https://frp1.fungs.cn/wechat/pay/notify'
  #notifyUrl: 'https://qiyundongpin.cn/goapi/wechat/pay/notify'
  #certPath: '' # 证书
  #keyPath: '' # 秘钥
  #debug: false

wechatPay:
  mchId: '' # 商户号
  apiV2Key: ''
  #  notifyUrl: 'https://frp1.fungs.cn/wechat/pay/notify'
  notifyUrl: ''
  certPath: '' # 证书
  keyPath: '' # 秘钥
  debug: false
